/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('ant-design-vue/es')['Button']
    ConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    Page: typeof import('./src/components/layout/Page.vue')['default']
    Radio: typeof import('ant-design-vue/es')['Radio']
    RadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('ant-design-vue/es')['Tag']
  }
}
